### ISSUE TITLE
Running program error

### ISSUE THREAD

**Issue by GUOss369** [exoclime/HELIOS#1]
Hello, when I run the program HELIOS, how to solve the following situation?
ABORT - " ./input/300.h5 " not found!

**Comment by matejmalik** [comment]
Hi, thanks for trying out HELIOS! What you have is not a program error. You are missing the opacity file, which is a necessary input for the code. Unfortunately, the opacity file is very large and cannot be shared via GitHub. We are working on a solution to distribute pre-generated opacity tables. For the moment, it needs to be generated by running HELIOS-K, an opacity calculation software. See https://github.com/exoclime/HELIOS-K for the code and its description.
