### ISSUE TITLE
Generating k-tables Error: k-distribution construction failed...

### ISSUE THREAD

**Issue by zmantas** [exoclime/HELIOS#5]
Hi, k-table generation in v3 seems to require that the lower_limit is set higher than the minimum wavelength of the specific opacity, otherwise it errors out. This requires all opacities to be computed for the same range, but for databases like Dace the range varies. Maybe this is a bug or does it have to be processed this way now? Thanks.

**Comment by matejmalik** [comment]
Good catch! I just found out the same thing an hour ago and just fixed it. Please update and try again.

**Comment by zmantas** [comment]
Great! Thanks for the quick fix!
